### PR TITLE
hepstats now on Conda

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Thanks to @chrisburr!

Just adding the badge.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
For reference - see https://github.com/conda-forge/staged-recipes/pull/13765.

**Comment by marinang** [comment]
The *Format* and *docs* steps failed but this is not a big issue.

**Review by marinang — APPROVED** [review]

**Comment by eduardo-rodrigues** [comment]
Do you want to try and fix some? Or for a separate PR? In any case you should merge if happy - the boss :-).

**Comment by marinang** [comment]
It's just things that are not up to date, I think, so we can investigate in a separate PR.

**Comment by eduardo-rodrigues** [comment]
BTW, let me know in private what's your preferred way for keeping in touch - email, Gitter, etc. Thanks.

**Pull request merged**
